/* Generated by AN DISI Unibo */ 
package it.unibo.firefly3

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly3 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var X           = 2
				var Y           = 2
				var Timer       = 5000L
				val NATURAL     = 5000L
				val SYNC_PERIOD = 2000L
				var inSync      = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("firefly3 | periodo naturale=$NATURAL ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("waitToFlash") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitToFlash", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitToFlash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t06",targetState="flash",cond=whenTimeout("local_tout_"+name+"_waitToFlash"))   
					transition(edgeName="t07",targetState="handleObstacleDetected",cond=whenEvent("obstacleDetected"))
					transition(edgeName="t08",targetState="handleObstacleClear",cond=whenEvent("obstacleClear"))
				}	 
				state("flash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						 Timer = if (inSync) SYNC_PERIOD else NATURAL  
						CommUtils.outgreen("firefly3 | flash -> period=$Timer ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("handleObstacleDetected") { //this:State
					action { //it:State
						
									inSync = true
									Timer  = SYNC_PERIOD
						CommUtils.outred("firefly3 | OSTACOLO -> SYNC $SYNC_PERIOD ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("handleObstacleClear") { //this:State
					action { //it:State
						
									inSync = false
									Timer  = NATURAL
						CommUtils.outgreen("firefly3 | CLEAR -> $NATURAL ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
			}
		}
} 
