/* Generated by AN DISI Unibo */ 
package it.unibo.coordinator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Coordinator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var TargetVal = 0L
				val Y_Dur      = 5000L    
				val MAX_TIME   = 2147483647L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("coordinator | avviato. Sync tra 10s...")
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sendSync", cond=doswitch() )
				}	 
				state("sendSync") { //this:State
					action { //it:State
						 
									TargetVal = 1000L + Math.abs(java.util.Random().nextLong()) % 4001L 
									val MsgSync = "syncNow($TargetVal)"
						emit("syncNow", "$MsgSync" ) 
						CommUtils.outyellow("coordinator | SYNC -> target=$TargetVal ms. Transizione...")
						delay(Y_Dur)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sendComplete", cond=doswitch() )
				}	 
				state("sendComplete") { //this:State
					action { //it:State
						emit("syncComplete", "syncComplete(0)" ) 
						CommUtils.outyellow("coordinator | SYNC COMPLETE. Bloccate su target=$TargetVal ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_idle", 
				 	 					  scope, context!!, "local_tout_"+name+"_idle", MAX_TIME )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="idle",cond=whenTimeout("local_tout_"+name+"_idle"))   
				}	 
			}
		}
} 
