/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				val DMIN             = 100L
				val MEASURE_INTERVAL = 1000L
				val STEP             = 15L
				var dist             = 150L
				var lastObstacle     = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("sonar | DMIN=$DMIN cm  step=+-$STEP cm")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="measure", cond=doswitch() )
				}	 
				state("measure") { //this:State
					action { //it:State
						delay(MEASURE_INTERVAL)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkDistance", cond=doswitch() )
				}	 
				state("checkDistance") { //this:State
					action { //it:State
						
									val delta = (Math.random() * (STEP * 2 + 1)).toLong() - STEP
									dist = (dist + delta).coerceIn(0L, 200L)
						CommUtils.outyellow("sonar | dist=$dist cm")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="evalTransition", cond=doswitch() )
				}	 
				state("evalTransition") { //this:State
					action { //it:State
						if(  !lastObstacle && dist < DMIN  
						 ){ lastObstacle = true  
						emit("obstacleDetected", "obstacleDetected(0)" ) 
						CommUtils.outred("sonar | *** OSTACOLO  dist=$dist < DMIN=$DMIN ***")
						}
						if(  lastObstacle && dist >= DMIN  
						 ){ lastObstacle = false  
						emit("obstacleClear", "obstacleClear(0)" ) 
						CommUtils.outgreen("sonar | --- CLEAR  dist=$dist >= DMIN=$DMIN ---")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="measure", cond=doswitch() )
				}	 
			}
		}
} 
