/* Generated by AN DISI Unibo */ 
package it.unibo.firefly3

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly3 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var X             = 2
				var Y             = 2
				var Timer         = 5000L
				var currentPeriod = 5000L
				var targetPeriod  = 0L
				val K             = 0.15
				val K_trans       = 0.35
				var inTransition  = false
				var MyName        = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 MyName = name  
						CommUtils.outgreen("$MyName | periodo iniziale=5000ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("waitToFlash") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitToFlash", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitToFlash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t09",targetState="flash",cond=whenTimeout("local_tout_"+name+"_waitToFlash"))   
					transition(edgeName="t010",targetState="handleFlashObserved",cond=whenEvent("flashEvent"))
					transition(edgeName="t011",targetState="handleSyncNow",cond=whenEvent("syncNow"))
					transition(edgeName="t012",targetState="handleSyncComplete",cond=whenEvent("syncComplete"))
				}	 
				state("flash") { //this:State
					action { //it:State
						
									val MOn  = "cellstate($X,$Y,1)"
									val MOff = "cellstate($X,$Y,0)"
									val FEv  = "flashEvent($MyName)"
						forward("cellstate", "$MOn" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "$MOff" ,"griddisplay" ) 
						emit("flashEvent", "$FEv" ) 
						
									if (inTransition) {
										currentPeriod = (currentPeriod * (1.0 - K_trans) + targetPeriod * K_trans).toLong()
									}
									Timer = currentPeriod
						CommUtils.outgreen("$MyName | flash -> currentPeriod=$currentPeriod ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("handleFlashObserved") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("flashEvent(SOURCE)"), Term.createTerm("flashEvent(SOURCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val src = payloadArg(0)
												if (src != MyName) {
													Timer = (Timer * (1.0 - K)).toLong()
													if (Timer < 0L) Timer = 0L
												}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("handleSyncNow") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("syncNow(TARGET)"), Term.createTerm("syncNow(TARGET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												targetPeriod = payloadArg(0).toLong()
												inTransition = true
												Timer        = 100L
								CommUtils.outyellow("$MyName | transizione -> target=$targetPeriod ms")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
				state("handleSyncComplete") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("syncComplete(TICK)"), Term.createTerm("syncComplete(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												inTransition  = false
												currentPeriod = targetPeriod
												Timer         = targetPeriod
								CommUtils.outyellow("$MyName | LOCKED su $currentPeriod ms")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitToFlash", cond=doswitch() )
				}	 
			}
		}
} 
